<script>
import { TruthTableLevel } from "../levelbase";
// import TestTemplate from "./testTemplate.vue";

const fulladderLevel = new TruthTableLevel({
    name: "Full Adder",
    description: "",
    inputs: [
        "A",
        "B",
        "Cin"
    ],
    outputs: [
        "S",
        "Cout"
    ],
    availableGates: undefined,
    truthTable: [
        { inputs: [false, false, false], outputs: [false, false] },
        { inputs: [false, false, true], outputs: [true, false] },
        { inputs: [false, true, false], outputs: [true, false] },
        { inputs: [false, true, true], outputs: [false, true] },
        { inputs: [true, false, false], outputs: [true, false] },
        { inputs: [true, false, true], outputs: [false, true] },
        { inputs: [true, true, false], outputs: [false, true] },
        { inputs: [true, true, true], outputs: [true, true] },
      ],
    maxGateCount: 5,
    timeLimit: 300
})

export default fulladderLevel;
</script>

<template>
    <div>
        <p>
            <b>What is a Full Adder?</b> - A full adder is a combinational logic circuit used to perform binary
            addition.

            <br /><br />It takes three inputs:<br />
            <b>A</b>: First binary digit.<br />
            <b>B</b>: Second binary digit.<br />
            <b>Carry-in (Cin)</b>: Carry from a previous addition.<br />
            <br />It produces two outputs:<br />

            <b>Sum (S)</b>: The binary sum of the inputs.<br />
            <b>Carry-out (Cout)</b>: The carry generated by the addition, passed to the next stage in multi-bit
            addition.<br />

            <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Full-adder.svg/1280px-Full-adder.svg.png" class="diagram"></img>


            <br /><b>Why is it important?</b> - Full adders are the building blocks for constructing arithmetic circuits
            in digital systems, such as CPUs and ALUs. When chained together, they enable the addition of multi-bit
            binary numbers, a core operation in computing.

            <a href="https://en.wikipedia.org/wiki/Adder_(electronics)#Full_adder" class="readmore">Read More</a>

        </p>
    </div>
</template>

<!-- style={{textAlign: "right", display: "inline-block", width: "100%" -->

<style scoped>
.diagram {
    width: 400px;
    margin-left: auto;
    margin-right: auto;
    display: block;
    background-color: rgba(255, 255, 255, 0.2);
    border-radius: 1em;
}

.readmore {
    text-align: right !important;
    display: inline-block;
    width: 100%;
}
</style>